services:
  database:
    image: postgres:18.4
    container_name: postgres
    ports: 
      - 5432:5432
    env_file:
      - /root/.db.env
    volumes:
      - beautyDB:/var/lib/postgresql

  panel:
    image: dpage/pgadmin4:9.16
    container_name: admin-panel
    ports:
      - 7000:80
    env_file:
      - /root/.admin.env
    environment:
      - TZ=Europe/Kyiv
volumes:
  beautyDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/beautyDB"