services:
  web:
    image: backend:latest
    container_name: beauty-web
    command: >
      sh -c "
        python manage.py migrate &&
        (python manage.py createsuperuser --noinput || true) &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - /root/.db.env
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
  celery:
    image: backend:latest
    container_name: celery_worker
    command: celery -A config worker -l info
    env_file:
      - /root/.db.env
    depends_on:
      - redis

  beat:
    image: backend:latest
    container_name: celery_beat
    command: celery -A config beat -l info
    env_file:
      - /root/.db.env
    depends_on:
      - redis

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"
  database:
    image: postgis/postgis:18-3.6
    container_name: postgis
    ports: 
      - 5432:5432
    env_file:
      - /root/.db.env
    volumes:
      - beautyDB:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  panel:
    image: dpage/pgadmin4:9.16
    container_name: admin-panel
    ports:
      - 7000:80
    env_file:
      - /root/.admin.env
    environment:
      - TZ=Europe/Kyiv
volumes:
  beautyDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/beautyDB"